// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "zpwoot Support",
            "url": "https://github.com/your-org/zpwoot",
            "email": "support@zpwoot.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Get basic information about the service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Service Information",
                "responses": {
                    "200": {
                        "description": "Service information",
                        "schema": {
                            "$ref": "#/definitions/InfoResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the service and database are healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a new WhatsApp session with the specified configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Create WhatsApp Session",
                "parameters": [
                    {
                        "description": "Session configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Session created successfully",
                        "schema": {
                            "$ref": "#/definitions/SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Session already exists",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves a list of all WhatsApp sessions with their current status (without QR codes)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "List WhatsApp Sessions",
                "responses": {
                    "200": {
                        "description": "List of sessions (without QR codes)",
                        "schema": {
                            "$ref": "#/definitions/APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/connect": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Connects a WhatsApp session. If already connected, returns current status with appropriate message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Connect WhatsApp Session",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session connected successfully or already connected",
                        "schema": {
                            "$ref": "#/definitions/SessionStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Connection error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Permanently deletes a WhatsApp session and all associated data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Delete WhatsApp Session",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Deletion error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/disconnect": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Disconnects an active WhatsApp session temporarily. If already disconnected, returns current status with appropriate message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Disconnect WhatsApp Session",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session disconnected successfully or already disconnected",
                        "schema": {
                            "$ref": "#/definitions/SessionStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Disconnection error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves detailed information about a specific WhatsApp session (without QR code)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Get WhatsApp Session",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session information (without QR code)",
                        "schema": {
                            "$ref": "#/definitions/SessionListInfo"
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Logs out a WhatsApp session permanently. Unlinks device from WhatsApp. Requires QR scan to reconnect.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Logout WhatsApp Session",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session logged out successfully",
                        "schema": {
                            "$ref": "#/definitions/SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Logout error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/qr": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves the QR code for WhatsApp session authentication. Scan with WhatsApp mobile app.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Get QR Code",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "QR code data",
                        "schema": {
                            "$ref": "#/definitions/QRCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Session already connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "QR code generation error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/audio": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send an audio message to a WhatsApp contact. Supports Base64, URL, or file path. Supports reply/quote using contextInfo. Set viewOnce to true to send as a view-once message that disappears after being viewed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send audio message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Audio message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendAudioMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or media processing error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/contact": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send a single contact card to a WhatsApp contact. VCard is auto-generated if not provided. Supports reply/quote using contextInfo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send contact message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Contact message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendContactMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/contacts": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send multiple contacts in a single message using ContactsArrayMessage. All contacts are sent in one message, not as separate messages. VCard is auto-generated for each contact if not provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send multiple contacts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Contacts array message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendContactsArrayMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contacts sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/document": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send a document message to a WhatsApp contact. Supports Base64, URL, or file path. Supports reply/quote using contextInfo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send document message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Document message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendDocumentMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or media processing error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/image": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send an image message to a WhatsApp contact with optional caption. Supports Base64, URL, or file path. Supports reply/quote using contextInfo. Set viewOnce to true to send as a view-once message that disappears after being viewed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send image message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Image message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendImageMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or media processing error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/location": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send a location message to a WhatsApp contact with latitude, longitude, and optional name/address. Supports reply/quote using contextInfo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send location message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Location message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendLocationMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/poll": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send a poll message to a WhatsApp contact with multiple options. Supports single or multiple selection.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send poll message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Poll message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendPollMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Poll sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/reaction": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send a reaction (emoji) to a specific message. Use empty string to remove reaction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send reaction message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reaction message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendReactionMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reaction sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/sticker": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send a sticker message to a WhatsApp contact. Supports Base64, URL, or file path. Image will be converted to WebP format.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send sticker message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Sticker message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendStickerMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sticker sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or media processing error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/text": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send a simple text message to a WhatsApp contact. Supports reply/quote using contextInfo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send text message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Text message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendTextMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{sessionId}/send/message/video": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send a video message to a WhatsApp contact with optional caption. Supports Base64, URL, or file path. Supports reply/quote using contextInfo. Set viewOnce to true to send as a view-once message that disappears after being viewed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send video message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Video message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SendVideoMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "schema": {
                            "$ref": "#/definitions/SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or media processing error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Session not connected",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/ErrorInfo"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-01-15T10:30:00Z"
                }
            }
        },
        "ContactInfo": {
            "type": "object",
            "required": [
                "name",
                "phone"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "vcard": {
                    "type": "string",
                    "example": "BEGIN:VCARD\nVERSION:3.0\nFN:John Doe\nTEL:+5511999999999\nEND:VCARD"
                }
            }
        },
        "ContextInfo": {
            "type": "object",
            "properties": {
                "participant": {
                    "type": "string",
                    "example": "5511888888888@s.whatsapp.net"
                },
                "quotedId": {
                    "type": "string",
                    "example": "3EB0A9253FA64269E11C9D"
                },
                "stanzaId": {
                    "type": "string",
                    "example": "3EB0A9253FA64269E11C9D"
                }
            }
        },
        "ContextInfoRequest": {
            "type": "object",
            "properties": {
                "participant": {
                    "type": "string",
                    "example": "5511888888888@s.whatsapp.net"
                },
                "stanzaId": {
                    "type": "string",
                    "example": "3EB0A9253FA64269E11C9D"
                }
            }
        },
        "CreateSessionRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "my-session"
                },
                "qrCode": {
                    "type": "boolean",
                    "example": true
                },
                "settings": {
                    "$ref": "#/definitions/SessionSettings"
                }
            }
        },
        "ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "validation_error"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "type": "string",
                    "example": "Validation failed"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "validation_error"
                },
                "message": {
                    "type": "string",
                    "example": "name is required"
                }
            }
        },
        "HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "zpwoot"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "InfoResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "zpwoot WhatsApp API is running"
                },
                "service": {
                    "type": "string",
                    "example": "zpwoot"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "ProxySettings": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "host": {
                    "type": "string",
                    "example": "proxy.example.com"
                },
                "pass": {
                    "type": "string",
                    "example": "proxyPass123"
                },
                "port": {
                    "type": "string",
                    "example": "8080"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "http",
                        "https",
                        "socks5"
                    ],
                    "example": "http"
                },
                "user": {
                    "type": "string",
                    "example": "proxyUser123"
                }
            }
        },
        "QRCodeResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string",
                    "example": "2025-01-15T10:35:00Z"
                },
                "qrCode": {
                    "type": "string",
                    "example": "2@abc123..."
                },
                "qrCodeBase64": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
                },
                "status": {
                    "type": "string",
                    "example": "generated"
                }
            }
        },
        "SendAudioMessageRequest": {
            "type": "object",
            "required": [
                "file",
                "phone"
            ],
            "properties": {
                "contextInfo": {
                    "$ref": "#/definitions/ContextInfoRequest"
                },
                "file": {
                    "type": "string",
                    "example": "https://example.com/audio.mp3"
                },
                "fileName": {
                    "type": "string",
                    "example": "audio.mp3"
                },
                "mimeType": {
                    "type": "string",
                    "example": "audio/mpeg"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "viewOnce": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "SendContactMessageRequest": {
            "type": "object",
            "required": [
                "contact",
                "phone"
            ],
            "properties": {
                "contact": {
                    "$ref": "#/definitions/ContactInfo"
                },
                "contextInfo": {
                    "$ref": "#/definitions/ContextInfoRequest"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                }
            }
        },
        "SendContactsArrayMessageRequest": {
            "type": "object",
            "required": [
                "contacts",
                "phone"
            ],
            "properties": {
                "contacts": {
                    "description": "Array of contacts sent in a single message",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/ContactInfo"
                    }
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                }
            }
        },
        "SendDocumentMessageRequest": {
            "type": "object",
            "required": [
                "file",
                "phone"
            ],
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "Important document attached"
                },
                "contextInfo": {
                    "$ref": "#/definitions/ContextInfoRequest"
                },
                "file": {
                    "type": "string",
                    "example": "https://example.com/document.pdf"
                },
                "fileName": {
                    "type": "string",
                    "example": "document.pdf"
                },
                "mimeType": {
                    "type": "string",
                    "example": "application/pdf"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                }
            }
        },
        "SendImageMessageRequest": {
            "type": "object",
            "required": [
                "file",
                "phone"
            ],
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "Check out this beautiful image!"
                },
                "contextInfo": {
                    "$ref": "#/definitions/ContextInfoRequest"
                },
                "file": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "fileName": {
                    "type": "string",
                    "example": "image.jpg"
                },
                "mimeType": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "viewOnce": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "SendLocationMessageRequest": {
            "type": "object",
            "required": [
                "latitude",
                "longitude",
                "phone"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Av. Paulista, 1578 - Bela Vista, São Paulo - SP"
                },
                "contextInfo": {
                    "$ref": "#/definitions/ContextInfoRequest"
                },
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90,
                    "example": -23.55052
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180,
                    "example": -46.633308
                },
                "name": {
                    "type": "string",
                    "example": "São Paulo"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                }
            }
        },
        "SendMessageResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Hello! This is a test message."
                },
                "contextInfo": {
                    "$ref": "#/definitions/ContextInfo"
                },
                "id": {
                    "type": "string",
                    "example": "3EB0A9253FA64269E11C9D"
                },
                "status": {
                    "type": "string",
                    "example": "sent"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1696570882
                },
                "to": {
                    "type": "string",
                    "example": "5511999999999@s.whatsapp.net"
                },
                "type": {
                    "type": "string",
                    "example": "text"
                }
            }
        },
        "SendPollMessageRequest": {
            "type": "object",
            "required": [
                "name",
                "options",
                "phone",
                "selectableOptionsCount"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "What's your favorite color?"
                },
                "options": {
                    "type": "array",
                    "maxItems": 12,
                    "minItems": 2,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Red",
                        "Blue",
                        "Green",
                        "Yellow"
                    ]
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "selectableOptionsCount": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                }
            }
        },
        "SendReactionMessageRequest": {
            "type": "object",
            "required": [
                "messageId",
                "phone",
                "reaction"
            ],
            "properties": {
                "fromMe": {
                    "description": "FromMe indicates if the message being reacted to was sent by us\nCan be set explicitly or by using \"me:\" prefix in MessageID\nExample: \"me:3EB0C767D0D1A6F4FD29\" or set FromMe: true",
                    "type": "boolean",
                    "example": false
                },
                "messageId": {
                    "type": "string",
                    "example": "3EB0C767D0D1A6F4FD29"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "reaction": {
                    "type": "string",
                    "example": "👍"
                }
            }
        },
        "SendStickerMessageRequest": {
            "type": "object",
            "required": [
                "file",
                "phone"
            ],
            "properties": {
                "contextInfo": {
                    "$ref": "#/definitions/ContextInfoRequest"
                },
                "file": {
                    "type": "string",
                    "example": "https://example.com/sticker.webp"
                },
                "fileName": {
                    "type": "string",
                    "example": "sticker.webp"
                },
                "mimeType": {
                    "type": "string",
                    "example": "image/webp"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                }
            }
        },
        "SendTextMessageRequest": {
            "type": "object",
            "required": [
                "phone",
                "text"
            ],
            "properties": {
                "contextInfo": {
                    "$ref": "#/definitions/ContextInfoRequest"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "text": {
                    "type": "string",
                    "example": "Hello! This is a test message from zpwoot API."
                }
            }
        },
        "SendVideoMessageRequest": {
            "type": "object",
            "required": [
                "file",
                "phone"
            ],
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "Watch this amazing video!"
                },
                "contextInfo": {
                    "$ref": "#/definitions/ContextInfoRequest"
                },
                "file": {
                    "type": "string",
                    "example": "https://example.com/video.mp4"
                },
                "fileName": {
                    "type": "string",
                    "example": "video.mp4"
                },
                "mimeType": {
                    "type": "string",
                    "example": "video/mp4"
                },
                "phone": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "viewOnce": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "SessionListInfo": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean",
                    "example": true
                },
                "connectedAt": {
                    "type": "string",
                    "example": "2025-01-15T10:32:00Z"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2025-01-15T10:30:00Z"
                },
                "deviceJid": {
                    "type": "string",
                    "example": "5511999999999@s.whatsapp.net"
                },
                "lastSeen": {
                    "type": "string",
                    "example": "2025-01-15T10:35:00Z"
                },
                "name": {
                    "type": "string",
                    "example": "my-session"
                },
                "sessionId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "settings": {
                    "$ref": "#/definitions/SessionSettings"
                },
                "status": {
                    "type": "string",
                    "example": "connected"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2025-01-15T10:35:00Z"
                }
            }
        },
        "SessionResponse": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean",
                    "example": true
                },
                "connectedAt": {
                    "type": "string",
                    "example": "2025-01-15T10:32:00Z"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2025-01-15T10:30:00Z"
                },
                "deviceJid": {
                    "type": "string",
                    "example": "5511999999999@s.whatsapp.net"
                },
                "lastSeen": {
                    "type": "string",
                    "example": "2025-01-15T10:35:00Z"
                },
                "name": {
                    "type": "string",
                    "example": "my-session"
                },
                "qrCode": {
                    "type": "string",
                    "example": "2@abc123..."
                },
                "qrCodeBase64": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgo..."
                },
                "qrCodeExpiresAt": {
                    "type": "string",
                    "example": "2025-01-15T10:35:00Z"
                },
                "sessionId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "settings": {
                    "$ref": "#/definitions/SessionSettings"
                },
                "status": {
                    "type": "string",
                    "example": "connected"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2025-01-15T10:35:00Z"
                }
            }
        },
        "SessionSettings": {
            "type": "object",
            "properties": {
                "proxy": {
                    "$ref": "#/definitions/ProxySettings"
                },
                "webhook": {
                    "$ref": "#/definitions/WebhookSettings"
                }
            }
        },
        "SessionStatusResponse": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "message": {
                    "type": "string",
                    "example": "Session is already connected"
                },
                "status": {
                    "type": "string",
                    "example": "connected"
                }
            }
        },
        "WebhookSettings": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Message",
                        "Receipt",
                        "Connected"
                    ]
                },
                "secret": {
                    "type": "string",
                    "example": "supersecrettoken123"
                },
                "url": {
                    "type": "string",
                    "example": "https://api.example.com/webhook"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key for authentication. Use the value from .env file (API_KEY variable). Send as 'Authorization: your-api-key' (without Bearer prefix)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "WhatsApp session management operations",
            "name": "Sessions"
        },
        {
            "description": "Message sending and retrieval operations",
            "name": "Messages"
        },
        {
            "description": "Contact management operations",
            "name": "Contacts"
        },
        {
            "description": "Health check and system status",
            "name": "Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "zpwoot WhatsApp API",
	Description:      "A comprehensive WhatsApp Business API built with Go, following Clean Architecture principles.\nProvides endpoints for session management, messaging, contacts, groups, media handling, and integrations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
